/*******************************************************************************
 * Copyright (c) 2014, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @file        Foo.cpp
 * @copyright   (c) 2014 - Jean-David Gadina - www.xs-labs.com
 * @abstract    PIMPL - Example class
 */

#include "Foo.h"
#include "pimpl-private.h"

template<>
class PIMPL::Object< Foo >::IMPL
{
    public:
        
        IMPL( void )
        {
            std::cout << "PIMPL::Object< Foo >::IMPL CTOR" << std::endl;
            
            this->x = 0;
            this->y = 0;
        }
        
        IMPL( const IMPL & o )
        {
            std::cout << "PIMPL::Object< Foo >::IMPL CCTOR" << std::endl;
            
            this->x = o.x;
            this->y = o.y;
        }
        
        ~IMPL( void )
        {
            std::cout << "PIMPL::Object< Foo >::IMPL DTOR" << std::endl;
        }
        
        int x;
        int y;
};

template class PIMPL::Object< Foo >;

int Foo::GetX( void ) const
{
    return this->impl->x;
}

void Foo::SetX( int x )
{
    this->impl->x = x;
}

int Foo::GetY( void ) const
{
    return this->impl->y;
}

void Foo::SetY( int y )
{
    this->impl->y = y;
}

std::ostream & operator << ( std::ostream & os, const Foo & obj )
{
    os << "Foo< " << &obj << "> { X: " << obj.GetX() << " Y: " << obj.GetY() << " }";
    
    return os;
}
