/*******************************************************************************
 * Copyright (c) 2014, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

/*!
 * @file        main.cpp
 * @copyright   (c) 2014 - Jean-David Gadina - www.xs-labs.com
 * @abstract    PIMPL example
 */

#include <iostream>
#include "Foo.h"
#include "Bar.h"

int main( void )
{
    {
        Foo a1;
        Foo a2( a1 );
        Foo a3;
        
        a1.SetX( 1 );
        a1.SetY( 2 );
        
        std::cout << std::endl;
        
        a3 = a1;
        
        a1.SetX( 2 );
        
        std::cout << std::endl;
        std::cout << a1 << std::endl;
        std::cout << a2 << std::endl;
        std::cout << a3 << std::endl;
        std::cout << std::endl;
        
        Foo a4 = std::move( a1 );
        
        std::cout << std::endl;
        std::cout << a4 << std::endl;
        std::cout << std::endl;
    }
    
    std::cout << std::endl;
    
    {
        Bar b1;
        Bar b2( b1 );
        Bar b3;
        
        b1.SetX( 1 );
        b1.SetY( 2 );
        b1.SetZ( 3 );
        
        std::cout << std::endl;
        
        b3 = b1;
        
        b1.SetX( 2 );
        
        std::cout << std::endl;
        std::cout << b1 << std::endl;
        std::cout << b2 << std::endl;
        std::cout << b3 << std::endl;
        std::cout << std::endl;
        
        Bar b4 = std::move( b1 );
        
        std::cout << std::endl;
        std::cout << b4 << std::endl;
        std::cout << std::endl;
    }
    
    return 0;
}
